server:
  port: 50070
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      uri: mongodb://order_read_user:order_read_pass@mongodb_order_read:27017/order_read
      database: order_read

