server:
  port: 50040
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://postgres-delivery:5432/deliverydb
    username: deliveryuser
    password: deliverypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true