eureka:
  client:
    service-url:
      defaultZone: http://api-eureka-server-v1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

http-clients:
  internal:
    order:
      base-url: http://API-ORDER-SERVICE-V1
      timeout: 5s
    payment:
      base-url: http://API-PAYMENT-SERVICE-V1
      timeout: 5s
    restaurant-v1:
      base-url: http://API-RESTAURANT-SERVICE-V1
      timeout: 5s
    restaurant-v2:
      base-url: http://API-RESTAURANT-SERVICE-V2
      timeout: 5s
    delivery:
      base-url: http://API-DELIVERY-SERVICE-V1
      timeout: 5s
  external:
    visa:
      base-url: http://visa-service:52010/api/visa/
      timeout: 5s